---
- name: Update apt cache and install WireGuard
  ansible.builtin.apt:
    name: wireguard
    update_cache: yes
    state: present

- name: Ensure /etc/wireguard directory exists
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    mode: '0700'

- name: Template WireGuard configuration file
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'
  notify: Restart WireGuard

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: yes

- name: Enable and start WireGuard service
  ansible.builtin.systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started
